/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as PppRouteImport } from './routes/ppp'
import { Route as HelloRouteImport } from './routes/hello'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as ContentIndexRouteImport } from './routes/content/index'
import { Route as PostsDetailRouteImport } from './routes/posts.detail'
import { Route as ContentContentIdRouteImport } from './routes/content/$contentId'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const PppRoute = PppRouteImport.update({
  id: '/ppp',
  path: '/ppp',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloRoute = HelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsDetailRoute = PostsDetailRouteImport.update({
  id: '/posts/detail',
  path: '/posts/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentContentIdRoute = ContentContentIdRouteImport.update({
  id: '/content/$contentId',
  path: '/content/$contentId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/$locale/about',
  path: '/$locale/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hello': typeof HelloRoute
  '/ppp': typeof PppRoute
  '/test': typeof TestRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/content/$contentId': typeof ContentContentIdRoute
  '/posts/detail': typeof PostsDetailRoute
  '/content': typeof ContentIndexRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hello': typeof HelloRoute
  '/ppp': typeof PppRoute
  '/test': typeof TestRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/content/$contentId': typeof ContentContentIdRoute
  '/posts/detail': typeof PostsDetailRoute
  '/content': typeof ContentIndexRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hello': typeof HelloRoute
  '/ppp': typeof PppRoute
  '/test': typeof TestRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/content/$contentId': typeof ContentContentIdRoute
  '/posts/detail': typeof PostsDetailRoute
  '/content/': typeof ContentIndexRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/hello'
    | '/ppp'
    | '/test'
    | '/$locale/about'
    | '/content/$contentId'
    | '/posts/detail'
    | '/content'
    | '/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/hello'
    | '/ppp'
    | '/test'
    | '/$locale/about'
    | '/content/$contentId'
    | '/posts/detail'
    | '/content'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/hello'
    | '/ppp'
    | '/test'
    | '/$locale/about'
    | '/content/$contentId'
    | '/posts/detail'
    | '/content/'
    | '/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HelloRoute: typeof HelloRoute
  PppRoute: typeof PppRoute
  TestRoute: typeof TestRoute
  LocaleAboutRoute: typeof LocaleAboutRoute
  ContentContentIdRoute: typeof ContentContentIdRoute
  PostsDetailRoute: typeof PostsDetailRoute
  ContentIndexRoute: typeof ContentIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppp': {
      id: '/ppp'
      path: '/ppp'
      fullPath: '/ppp'
      preLoaderRoute: typeof PppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/detail': {
      id: '/posts/detail'
      path: '/posts/detail'
      fullPath: '/posts/detail'
      preLoaderRoute: typeof PostsDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$contentId': {
      id: '/content/$contentId'
      path: '/content/$contentId'
      fullPath: '/content/$contentId'
      preLoaderRoute: typeof ContentContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/$locale/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HelloRoute: HelloRoute,
  PppRoute: PppRoute,
  TestRoute: TestRoute,
  LocaleAboutRoute: LocaleAboutRoute,
  ContentContentIdRoute: ContentContentIdRoute,
  PostsDetailRoute: PostsDetailRoute,
  ContentIndexRoute: ContentIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
