/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as PppRouteImport } from './routes/ppp'
import { Route as HelloRouteImport } from './routes/hello'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PostRouteRouteImport } from './routes/post/route'
import { Route as ContentRouteRouteImport } from './routes/content/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as ContentIndexRouteImport } from './routes/content/index'
import { Route as TestingRedirectSsoWithReplaceRouteImport } from './routes/testing/redirect-sso-with-replace'
import { Route as TestingRedirectSsoWithLocationHrefRouteImport } from './routes/testing/redirect-sso-with-location-href'
import { Route as PostsDetailRouteImport } from './routes/posts.detail'
import { Route as ContentContentIdRouteImport } from './routes/content/$contentId'
import { Route as PostPostPathlessLayoutRouteRouteImport } from './routes/post/_postPathlessLayout/route'
import { Route as PostPostIdIndexRouteImport } from './routes/post/$postId/index'
import { Route as PostPostPathlessLayoutTestRouteImport } from './routes/post/_postPathlessLayout/test'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const PppRoute = PppRouteImport.update({
  id: '/ppp',
  path: '/ppp',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloRoute = HelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRouteRoute = PostRouteRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRouteRoute = ContentRouteRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContentRouteRoute,
} as any)
const TestingRedirectSsoWithReplaceRoute =
  TestingRedirectSsoWithReplaceRouteImport.update({
    id: '/testing/redirect-sso-with-replace',
    path: '/testing/redirect-sso-with-replace',
    getParentRoute: () => rootRouteImport,
  } as any)
const TestingRedirectSsoWithLocationHrefRoute =
  TestingRedirectSsoWithLocationHrefRouteImport.update({
    id: '/testing/redirect-sso-with-location-href',
    path: '/testing/redirect-sso-with-location-href',
    getParentRoute: () => rootRouteImport,
  } as any)
const PostsDetailRoute = PostsDetailRouteImport.update({
  id: '/posts/detail',
  path: '/posts/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentContentIdRoute = ContentContentIdRouteImport.update({
  id: '/$contentId',
  path: '/$contentId',
  getParentRoute: () => ContentRouteRoute,
} as any)
const PostPostPathlessLayoutRouteRoute =
  PostPostPathlessLayoutRouteRouteImport.update({
    id: '/_postPathlessLayout',
    getParentRoute: () => PostRouteRoute,
  } as any)
const PostPostIdIndexRoute = PostPostIdIndexRouteImport.update({
  id: '/$postId/',
  path: '/$postId/',
  getParentRoute: () => PostRouteRoute,
} as any)
const PostPostPathlessLayoutTestRoute =
  PostPostPathlessLayoutTestRouteImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () => PostPostPathlessLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/content': typeof ContentRouteRouteWithChildren
  '/post': typeof PostPostPathlessLayoutRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/hello': typeof HelloRoute
  '/ppp': typeof PppRoute
  '/test': typeof TestRoute
  '/content/$contentId': typeof ContentContentIdRoute
  '/posts/detail': typeof PostsDetailRoute
  '/testing/redirect-sso-with-location-href': typeof TestingRedirectSsoWithLocationHrefRoute
  '/testing/redirect-sso-with-replace': typeof TestingRedirectSsoWithReplaceRoute
  '/content/': typeof ContentIndexRoute
  '/posts': typeof PostsIndexRoute
  '/post/test': typeof PostPostPathlessLayoutTestRoute
  '/post/$postId': typeof PostPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/post': typeof PostPostPathlessLayoutRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/hello': typeof HelloRoute
  '/ppp': typeof PppRoute
  '/test': typeof TestRoute
  '/content/$contentId': typeof ContentContentIdRoute
  '/posts/detail': typeof PostsDetailRoute
  '/testing/redirect-sso-with-location-href': typeof TestingRedirectSsoWithLocationHrefRoute
  '/testing/redirect-sso-with-replace': typeof TestingRedirectSsoWithReplaceRoute
  '/content': typeof ContentIndexRoute
  '/posts': typeof PostsIndexRoute
  '/post/test': typeof PostPostPathlessLayoutTestRoute
  '/post/$postId': typeof PostPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/content': typeof ContentRouteRouteWithChildren
  '/post': typeof PostRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/hello': typeof HelloRoute
  '/ppp': typeof PppRoute
  '/test': typeof TestRoute
  '/post/_postPathlessLayout': typeof PostPostPathlessLayoutRouteRouteWithChildren
  '/content/$contentId': typeof ContentContentIdRoute
  '/posts/detail': typeof PostsDetailRoute
  '/testing/redirect-sso-with-location-href': typeof TestingRedirectSsoWithLocationHrefRoute
  '/testing/redirect-sso-with-replace': typeof TestingRedirectSsoWithReplaceRoute
  '/content/': typeof ContentIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/post/_postPathlessLayout/test': typeof PostPostPathlessLayoutTestRoute
  '/post/$postId/': typeof PostPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/content'
    | '/post'
    | '/about'
    | '/hello'
    | '/ppp'
    | '/test'
    | '/content/$contentId'
    | '/posts/detail'
    | '/testing/redirect-sso-with-location-href'
    | '/testing/redirect-sso-with-replace'
    | '/content/'
    | '/posts'
    | '/post/test'
    | '/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/post'
    | '/about'
    | '/hello'
    | '/ppp'
    | '/test'
    | '/content/$contentId'
    | '/posts/detail'
    | '/testing/redirect-sso-with-location-href'
    | '/testing/redirect-sso-with-replace'
    | '/content'
    | '/posts'
    | '/post/test'
    | '/post/$postId'
  id:
    | '__root__'
    | '/'
    | '/content'
    | '/post'
    | '/about'
    | '/hello'
    | '/ppp'
    | '/test'
    | '/post/_postPathlessLayout'
    | '/content/$contentId'
    | '/posts/detail'
    | '/testing/redirect-sso-with-location-href'
    | '/testing/redirect-sso-with-replace'
    | '/content/'
    | '/posts/'
    | '/post/_postPathlessLayout/test'
    | '/post/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentRouteRoute: typeof ContentRouteRouteWithChildren
  PostRouteRoute: typeof PostRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  HelloRoute: typeof HelloRoute
  PppRoute: typeof PppRoute
  TestRoute: typeof TestRoute
  PostsDetailRoute: typeof PostsDetailRoute
  TestingRedirectSsoWithLocationHrefRoute: typeof TestingRedirectSsoWithLocationHrefRoute
  TestingRedirectSsoWithReplaceRoute: typeof TestingRedirectSsoWithReplaceRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppp': {
      id: '/ppp'
      path: '/ppp'
      fullPath: '/ppp'
      preLoaderRoute: typeof PppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/': {
      id: '/content/'
      path: '/'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof ContentRouteRoute
    }
    '/testing/redirect-sso-with-replace': {
      id: '/testing/redirect-sso-with-replace'
      path: '/testing/redirect-sso-with-replace'
      fullPath: '/testing/redirect-sso-with-replace'
      preLoaderRoute: typeof TestingRedirectSsoWithReplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing/redirect-sso-with-location-href': {
      id: '/testing/redirect-sso-with-location-href'
      path: '/testing/redirect-sso-with-location-href'
      fullPath: '/testing/redirect-sso-with-location-href'
      preLoaderRoute: typeof TestingRedirectSsoWithLocationHrefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/detail': {
      id: '/posts/detail'
      path: '/posts/detail'
      fullPath: '/posts/detail'
      preLoaderRoute: typeof PostsDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$contentId': {
      id: '/content/$contentId'
      path: '/$contentId'
      fullPath: '/content/$contentId'
      preLoaderRoute: typeof ContentContentIdRouteImport
      parentRoute: typeof ContentRouteRoute
    }
    '/post/_postPathlessLayout': {
      id: '/post/_postPathlessLayout'
      path: ''
      fullPath: '/post'
      preLoaderRoute: typeof PostPostPathlessLayoutRouteRouteImport
      parentRoute: typeof PostRouteRoute
    }
    '/post/$postId/': {
      id: '/post/$postId/'
      path: '/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdIndexRouteImport
      parentRoute: typeof PostRouteRoute
    }
    '/post/_postPathlessLayout/test': {
      id: '/post/_postPathlessLayout/test'
      path: '/test'
      fullPath: '/post/test'
      preLoaderRoute: typeof PostPostPathlessLayoutTestRouteImport
      parentRoute: typeof PostPostPathlessLayoutRouteRoute
    }
  }
}

interface ContentRouteRouteChildren {
  ContentContentIdRoute: typeof ContentContentIdRoute
  ContentIndexRoute: typeof ContentIndexRoute
}

const ContentRouteRouteChildren: ContentRouteRouteChildren = {
  ContentContentIdRoute: ContentContentIdRoute,
  ContentIndexRoute: ContentIndexRoute,
}

const ContentRouteRouteWithChildren = ContentRouteRoute._addFileChildren(
  ContentRouteRouteChildren,
)

interface PostPostPathlessLayoutRouteRouteChildren {
  PostPostPathlessLayoutTestRoute: typeof PostPostPathlessLayoutTestRoute
}

const PostPostPathlessLayoutRouteRouteChildren: PostPostPathlessLayoutRouteRouteChildren =
  {
    PostPostPathlessLayoutTestRoute: PostPostPathlessLayoutTestRoute,
  }

const PostPostPathlessLayoutRouteRouteWithChildren =
  PostPostPathlessLayoutRouteRoute._addFileChildren(
    PostPostPathlessLayoutRouteRouteChildren,
  )

interface PostRouteRouteChildren {
  PostPostPathlessLayoutRouteRoute: typeof PostPostPathlessLayoutRouteRouteWithChildren
  PostPostIdIndexRoute: typeof PostPostIdIndexRoute
}

const PostRouteRouteChildren: PostRouteRouteChildren = {
  PostPostPathlessLayoutRouteRoute:
    PostPostPathlessLayoutRouteRouteWithChildren,
  PostPostIdIndexRoute: PostPostIdIndexRoute,
}

const PostRouteRouteWithChildren = PostRouteRoute._addFileChildren(
  PostRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentRouteRoute: ContentRouteRouteWithChildren,
  PostRouteRoute: PostRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  HelloRoute: HelloRoute,
  PppRoute: PppRoute,
  TestRoute: TestRoute,
  PostsDetailRoute: PostsDetailRoute,
  TestingRedirectSsoWithLocationHrefRoute:
    TestingRedirectSsoWithLocationHrefRoute,
  TestingRedirectSsoWithReplaceRoute: TestingRedirectSsoWithReplaceRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
